### ISSUE TITLE
(jxa-bundler) Missing function parseMappingArgument

### ISSUE THREAD

**Issue by loic-roux-404** [aheissenberger/macos-jxa-bundler#1]
`$ jxabundler --define CMC_API_KEY="$CMC_API_KEY" -t app` gives
ReferenceError: parseMappingArgument is not defined

    at nc (/Users/loic/Scripts/apple-numbers-pull-crypto/node_modules/jxabundler/dist/cli.js:2:242794)
    at /Users/loic/Scripts/apple-numbers-pull-crypto/node_modules/jxabundler/dist/cli.js:2:250672

Code is commented here : https://github.com/aheissenberger/macos-jxa-bundler/blob/92bf96b4f207aecaf40d528f0356cee030e9cde4/packages/jxabundler/src/index.js#L27

**Comment by aheissenberger** [comment]
I have a look at this on Monday

**Comment by aheissenberger** [comment]
sorry for my late response - problem is fixed

**Comment by loic-roux-404** [comment]
Thanks i don't remember but i finished the work on this
