### ISSUE TITLE
$ symbol in output file clashes with global $

### ISSUE THREAD

**Issue by rochwu** [aheissenberger/macos-jxa-bundler#2]
Was a fun error to track down!

Seems that microbundle declares variable `$` when the alphabet is exhausted enough which then clashes with the `$` reserved by webkit. I saw that you already replace certain strings in `jxabundler` so I thought you might wanna do one for `$` too. Or maybe scope it 🤔 

So far I've seen it used as a variable and an object, so I hacked a script to watch + replace with regex `/[$]((?=[=])|(?=[,])|(?=[.]))/g` haven't seen it invoked `$(` yet 🤷‍♂️ 

Mini demo on `Can't create duplicate variable that shadows a global property: '$'`
<img width="324" alt="Global $" src="https://user-images.githubusercontent.com/6355568/161044376-b496c1ab-665f-47e2-8652-2f0b2dda4ebf.png">

**Comment by aheissenberger** [comment]
@rochwu the global "$" variable is defined by JXA and is the bridge to ObjectiveC System Calls - e.g.

`$.NSFileHandle.fileHandleForWritingAtPath( oFullPath);`

There is no way to avoid this when transforming, but you can handle it by using functions or simple closures to avoid variable   name clash:

```js
#!/usr/bin/env osascript -l JavaScript
{
const $ =123;
}
```
